### ISSUE TITLE
Arbitrary z-[10] value is not being removed by overrides

### ISSUE THREAD

**Issue by tbaustin** [dcastil/tailwind-merge#115]
I have something like `twMerge("z-[100] z-20")` resulting in `"z-[100] z-20"` so it's not overriding correctly. And then tailwind uses the arbitrary value and the override doesn't work.

**Comment by dcastil** [comment]
Hey @tbaustin! 👋

Thats a bug indeed. I pushed a fix in [`v1.5.1`](https://github.com/dcastil/tailwind-merge/releases/tag/v1.5.1). Let me know if the issue still persists.

**Comment by tbaustin** [comment]
> Hey @tbaustin! 👋
> 
> Thats a bug indeed. I pushed a fix in [`v1.5.1`](https://github.com/dcastil/tailwind-merge/releases/tag/v1.5.1). Let me know if the issue still persists.

That worked thanks :D
