### ISSUE TITLE
matchAll Polyfill

### ISSUE THREAD

**Issue by schonfeld** [dcastil/tailwind-merge#132]
We've been seeing some client side error logs re `.matchAll()` calls evaluating to `undefined`. After a bit of digging, we realized that all of those exceptions originate on older-ish browsers. Nonetheless, this is an issue for us (and I suspect others, too). Specifically, the issue stems from this line: https://github.com/dcastil/tailwind-merge/blob/a703309b6811b8b798b1a8cd2d1db3ac06811b36/src/lib/merge-classlist.ts#L83

I'm curious if you've given thought to adding a matchAll polyfill, or using a different approach to matching?

**Comment by charkour** [comment]
For a workaround, you could consider using the npm package [string.prototype.matchall](https://www.npmjs.com/package/string.prototype.matchall) to polyfill. 

It provides a shim, so at the start of your app, I think you could call `const matchAll = require('string.prototype.matchall'); matchAll.shim();` to polyfill.

Which browser are you using?

**Comment by schonfeld** [comment]
Right -- I've impl'd that polyfill and it seems to work for us. But it took us an hour to realize this was the issue. Figured I'd post here to save others some time.

I'm able to reproduce this on Chrome 70.x on Mac. It's difficult to run multiple Chrome versions on the same machine, but you can download an old build of Chromium and easily run that side-by-side. Here's the version I'm using: [version: 70.0.3538.124](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/587811/)

Here's a sample stacktrace, although, the issue is rather straight forward:

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/130491/185666700-109a7096-c966-44d2-af2c-d03197fe2926.png">

**Comment by dcastil** [comment]
Just checked on caniuse and `matchAll` is available for 93.59% of global users. I'd say for a library like tailwind-merge that probably isn't enough, especially since I think I should be able to replace it easily. I'll implement a fix for this.

@schonfeld out of curiosity, what browsers do you need to support? Do you have a defined policy for that?

**Comment by schonfeld** [comment]
> Just checked on caniuse and `matchAll` is available for 93.59% of global users. I'd say for a library like tailwind-merge that probably isn't enough, especially since I think I should be able to replace the functionality easily. I'll implement a fix for this.
> 
> @schonfeld out of curiosity, what browsers do you need to support? Do you have a defined policy for that?

I don't really a policy, per se. We typically try to not be bothered by older/out-dated browsers, but this issue seemed to affect a non-negligible portion of our daily users, somewhere in the 200 uniques per day... It seems to affect _mostly_ mobile browsers. I suspect because those are usually tied to OS updates, and some folks are unable to upgrade on older devices...

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/130491/185714728-7f538667-c8cc-462a-96ef-390fed643b87.png">

**Comment by dcastil** [comment]
Okay, that makes sense. Thanks for the info!

**Comment by dcastil** [comment]
@schonfeld you can now `<my-favorite-package-manager> add tailwind-merge@dev` where `matchAll` isn't used anymore, so you should be able to remove your matchAll polyfill as well. A v1.6.0 will come in the coming days.

**Comment by schonfeld** [comment]
Confirmed working on latest v1.6.0. Thanks so much, @dcastil !
