### ISSUE TITLE
`h-min` does not override `h-10`

### ISSUE THREAD

**Issue by tbaustin** [dcastil/tailwind-merge#145]
On most recent version.

Maybe this isn't supposed to work? But `h-min` isn't removing the `h-10`. 

![image](https://user-images.githubusercontent.com/14001400/193087239-c8b07f9a-ccd2-4def-b5bd-18a7547d605d.png)

**Comment by dcastil** [comment]
Hey @tbaustin! 👋 

It's supposed to work. I'm releasing a fix in a few mins.
