### ISSUE TITLE
Grid rules like col-start-1 are being discarded on merge

### ISSUE THREAD

**Issue by Markkop** [dcastil/tailwind-merge#176]
Hey, there!
I have something like

```js
<Hero className="sm:col-start-1 lg:col-start-2 sm:col-span-12 lg:col-span-5" />
```
and

```js
import { twMerge } from 'tailwind-merge'

export function Hero({ className = '' }) {
  return (
    <div
      className={twMerge('grid z-50 sm:px-8 lg:px-0 content-center', className)}
    >
    // ...
    </div>
  )
}
```

But the end result is `grid z-50 sm:px-8 lg:px-0 content-center sm:col-span-12 lg:col-span-5`, the class rules `sm:col-start-1 lg:col-start-2` are not being merged.

Can you take a look when you're available?
Thanks!

**Comment by dcastil** [comment]
Hey @Markkop! 👋 

You're right, I accidentally put those into conflict, probably got confused with Tailwind's naming. https://github.com/dcastil/tailwind-merge/blob/v1.8.0/src/lib/default-config.ts#L1546-L1547

I'll push a fix shortly.

**Comment by Markkop** [comment]
Awesome, thank you very much @dcastil!
