### ISSUE TITLE
flex-grow should override flex-shrink

### ISSUE THREAD

**Issue by hazeled** [dcastil/tailwind-merge#180]
`twMerge("flex-shrink", "flex-grow")` should return just `flex-grow`, but it returns `flex-shrink flex-grow`. `flex-shrink` and `flex-grow` are incompatible css classes, and their behavior overrides eachother.

**Comment by dcastil** [comment]
Hey @hazeled! 👋 

Those are different properties which are compatible with each other!
- `flex-shrink` is about how a flex child is allowed to shrink beyond its intrinsic size if there isn't enough space available in the flex container
- `flex-grow` is about how a flex child is allowed to grow beyond its intrinsic size if there is free space available in the flex container.

Using both together means that you control both how the element shrinks and grows. E.g. `flex-shrink-0 flex-grow` means that the element can't shrink below its intrinsic size but can grow bigger.

You can read more about that in https://developer.mozilla.org/en-US/docs/Web/CSS/flex.

**Comment by hazeled** [comment]
Hey, sorry about that! After reviewing the documentation, you're completely correct. I had misunderstood the `flex-shrink` property. Thank you so much!!
