### ISSUE TITLE
leading (line-height) not generated with tailwind-merge

### ISSUE THREAD

**Issue by phatify** [dcastil/tailwind-merge#187]
I'm trying to override the `leading `className property but currently those not generated in output.

not work as expected:
`twMerge('leading-normal leading-[2.5rem] font-bold text-md'); // output: 'font-bold text-md'`

work as expected:
`twMerge('leading-normal font-bold text-md  leading-[2.5rem]'); // output: 'font-bold text-md leading-[2.5rem]'`

**Comment by dcastil** [comment]
Hey @phatify! 👋

That is intended because in the default config `text-md` adds a line-height CSS property, overriding `leading-[2.5rem]`.

More info here https://github.com/dcastil/tailwind-merge/issues/59#issuecomment-976400644

**Comment by dcastil** [comment]
A console warning could be annoying to users, especially if it appears over and over. But maybe I can add an FAQ to the documentation about this.

**Comment by mrienstra** [comment]
@phatify, see https://github.com/dcastil/tailwind-merge/issues/218#issuecomment-1559982198
