### ISSUE TITLE
Arbitrary properties should not be overridden when a type is specified

### ISSUE THREAD

**Issue by brandonmcconnell** [dcastil/tailwind-merge#193]
When I use this class string: `border-b border-[color:rgb(var(--color-gray-500-rgb)/50%))]` 

`border-[color:rgb(var(--color-gray-500-rgb)/50%))]` overrides `border-b`

I think it could be really useful to detect when a type is defined on an arbitrary property and override it accordingly (or don't when not).

In this case, `border-[color:`… should not override `border-b`

**Comment by dcastil** [comment]
Hey @brandonmcconnell! 👋

Thanks for reporting this! I'm working on a fix.

**Comment by brandonmcconnell** [comment]
Thanks! @dcastil

**Comment by dcastil** [comment]
I discovered [another bug](https://github.com/dcastil/tailwind-merge/issues/194) I want to fix, so it will take a bit until I release a new version. If you need the fix right now, you can install `tailwind-merge@1.9.0-dev.b7452f6249886e8d99990e8c73ff86d6023b457d` already until a new prod release is out.
