### ISSUE TITLE
bg-image defined in theme conflict with bg-colors

### ISSUE THREAD

**Issue by kevinfoerster** [dcastil/tailwind-merge#201]
when defining a background-image in the tailwind config and use it as `bg-circle-top` the  background color is discarded when using `twMerge`.

config:
```js
module.exports = {
  content: ["./components/**/*.{html,js,ts,tsx}"],
  theme: {
    backgroundImage: {
      "circles-top": "url('/assets/svg/TopLeft1pxOutline.svg')",
      "circles-bottom": "url('/assets/svg/BottomLeft1pxOutline.svg')",
    },
  }
}
```
this will discard `bg-green`
`className={twMerge("bg-green bg-circle-top")}`

but setting the image using arbitrary values works and the background-color aswell as the background image is applied.
`className={twMerge("bg-green  bg-[url('/assets/svg/BottomLeft1pxOutline.svg')]")}`

is there anyway around this? or add a configuration that allows `bg-circles-top` and `bg-circles-bottom` and `bg-colors`?

**Comment by dcastil** [comment]
Hey @kevinfoerster! 👋

You need to configure tailwind-merge to recognize those custom classes. [Here](https://github.com/dcastil/tailwind-merge/blob/v1.9.1/docs/recipes.md#adding-custom-scale-from-tailwind-config-to-tailwind-merge-config) is some documentation for this.

Basically this:

```ts
const twMerge = extendTailwindMerge({
    classGroups: {
        'bg-image': ['bg-circles-top', 'bg-circles-bottom']
    }
})
```

**Comment by kevinfoerster** [comment]
Thank you for pointing this out, I saw the function but could not put my problems and the problem it solves together 👍

**Comment by dcastil** [comment]
Ah alright. I think I need to phrase that recipe a little better.
