### ISSUE TITLE
`bg-opacity` overrides `bg-[color]`

### ISSUE THREAD

**Issue by juliancoleman** [dcastil/tailwind-merge#203]
I have a component with the following classes `"bg-base-black bg-opacity-[0.7]"`. The output className is `"bg-opacity-[0.7]"`. It appears that the issue happens specifically if I use an arbitrary value for the opacity. If I use `bg-opacity-75`, both classes are emitted.

**Comment by dcastil** [comment]
Hi @juliancoleman! 👋

Thanks for reporting this. I'm working on a fix.

**Comment by dcastil** [comment]
Ah I fixed this in [v1.9.1](https://github.com/dcastil/tailwind-merge/releases/tag/v1.9.1) already. Could you update to that version and let me know whether your issue got resolved?

**Comment by dcastil** [comment]
Closing this as this should be resolved. Let me know if you still have any issues.

**Comment by juliancoleman** [comment]
Thanks for the response! I apologize I didn't get back to this sooner. I hadn't been able to update to 1.9.1 because I was waiting on #192, which also appears to be merged. I'll go ahead and test it and if I have issues, I'll report back. If you hear nothing, assume everything went well :+1:
