### ISSUE TITLE
Can not override class with custom class in tailwind-merge

### ISSUE THREAD

**Issue by nguyenthanhan201** [dcastil/tailwind-merge#207]
this is my custom class btn
`.btn {
  @apply relative inline-flex min-w-16 cursor-pointer items-center justify-center rounded-lg leading-tight outline-none py-3 px-5 gap-2;
}`

then i use merge
`twMerge(
      "btn",
      classVariants(variant),
      className
    )`

**Comment by dcastil** [comment]
Hey @nguyenthanhan201! 👋

You need to configure tailwind-merge to understand your custom class. But I don't recommend using `@apply` together with tailwind-merge. Here is more info on that and an alternative way to do what you want: https://github.com/dcastil/tailwind-merge/blob/main/docs/recipes.md#extracting-classes-with-tailwinds-apply

**Comment by nguyenthanhan201** [comment]
> Hey @nguyenthanhan201! 👋
> 
> You need to configure tailwind-merge to understand your custom class. But I don't recommend using `@apply` together with tailwind-merge. Here is more info on that and an alternative way to do what you want: https://github.com/dcastil/tailwind-merge/blob/v1.10.0/docs/recipes.md#extracting-classes-with-tailwinds-apply

Thank for your help
