### ISSUE TITLE
Custom `fontSize` and `text-[color]` not merged correctly

### ISSUE THREAD

**Issue by hrasoa** [dcastil/tailwind-merge#217]
Repro: https://nu0yre-3000.csb.app/
Source: https://codesandbox.io/p/sandbox/friendly-meitner-nu0yre?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A7%2C%22endLineNumber%22%3A6%2C%22startColumn%22%3A7%2C%22startLineNumber%22%3A6%7D%5D

`tailwind.config.js`:
```js
module.exports = {
  content: ["./pages/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
    fontSize: {
      "display-2xl": [
        "4.5rem",
        { lineHeight: "5.625rem", letterSpacing: "-0.02em" },
      ],
    },
  },
  plugins: [],
};
```

Custom `twMerge` (`./src/tw-merge-custom.ts`):
```js
import { extendTailwindMerge } from 'tailwind-merge';

export const twMergeCustom = extendTailwindMerge({
    theme: {
        fontSize: ['display-2xl']
    }
}) 
```

Expected: `text-display-2xl text-blue-600`
Result: `text-blue-600`

**Comment by dcastil** [comment]
Hey @hrasoa! 👋

tailwind-merge doesn't support font-sizes in theme keys ([here](https://github.com/dcastil/tailwind-merge/blob/v1.12.0/docs/configuration.md#theme) is a list of all supported theme keys). You need to add that config into the `classGroups` object in the tailwind-merge config.

```ts
import { extendTailwindMerge } from https://github.com/dcastil/tailwind-merge;

export const twMergeCustom = extendTailwindMerge({
    classGroups: {
       'font-size': ['text-display-2xl']
    }
})
```

[Here](https://github.com/dcastil/tailwind-merge/blob/v1.12.0/docs/recipes.md#adding-custom-scale-from-tailwind-config-to-tailwind-merge-config) is more info on how to add custom Tailwind scales to tailwind-merge.

**Comment by hrasoa** [comment]
It's working thanks !
