### ISSUE TITLE
Class getting stripped out unnecessarily

### ISSUE THREAD

**Issue by brandonmcconnell** [dcastil/tailwind-merge#218]
I have this, roughly—

```ts
let computedClasses = cls(
  'inline-block text-base text-left font-semibold leading-tight',
  'text-xl'
);

console.log(computedClasses); // -> 'inline-block text-left font-semibold text-xl'
```

I can't figure out why `leading-tight` is getting removed.

Here is my implementation of `cls`:

```ts
import clsx, { type ClassValue } from 'clsx';
import { extendTailwindMerge, validators } from 'tailwind-merge';
import { spreadKeys } from '@carevoyance/calculations';

const trbl = ['t', 'r', 'b', 'l'];
const xy = ['x', 'y'];
const dirs = { trbl, xy, all: [...trbl, ...xy] };

const twMerge = extendTailwindMerge({
  classGroups: {
    shadow: [{
      shadow: [{
        ...spreadKeys(dirs.trbl, ['', 'inner', validators.isTshirtSize]),
        border: [
          '',
          validators.isNumber,
          validators.isArbitraryLength,
          spreadKeys(dirs.all, [validators.isNumber, validators.isArbitraryLength]),
        ],
      }],
    }],
  },
});

export const cls = (...inputs: ClassValue[]) => twMerge(clsx(...inputs));
```

---

Thanks for all the help, as always 🙏🏼

**Comment by dcastil** [comment]
Hey @brandonmcconnell! 👋

This is because `text-xl` also sets line-height (`line-height: 1.75rem;` to be exact). If you want to preserve `leading-tight`, you need to set it after `text-xl`.

It's similar to how `px-4 p-5` gets reduced to `p-5` because you want to override the paddings set by `px-4` but `p-5 px-4` stays intact because tailwind-merge sees that as a refinement to `p-5`.

**Comment by dcastil** [comment]
But I know that this is confusing. There were already [several](https://github.com/dcastil/tailwind-merge/issues/59) [issues](https://github.com/dcastil/tailwind-merge/issues/187) about this exact problem. Not many people know that Tailwind CSS is doing this. 🤔

**Comment by brandonmcconnell** [comment]
@dcastil Thanks for clarifying that! I believe—though I could be wrong—if you have both a `font-size` utility like `text-xs` and a `line-height` utility like `leading-tight`, `leading-_` will override the `line-height` regardless of the order (in pure TailwindCSS).

It would be great if tailwind-merge offered a setting to allow utilities like these and those you mentioned to not be considered conflicts and to allow TailwindCSS to handle their overrides naturally.

**Comment by brandonmcconnell** [comment]
Also, if they're considered conflicts and I set `leading-x` after `text-x`, does that mean that `leading` would be prioritized and the `text` utility would be removed instead, making it difficult/impossible to have both?

**Comment by dcastil** [comment]
If you put `leading-x` after `text-x`, both stay in there since you want to override the line-height of `text-x` but keep its font-size. The override happens through the CSS order in that case.

But e.g. think of a component that defines a line-height with `leading-x` inside and then you want to do `<MyComponent className="text-xl" />` (which then results in `twMerge('… leading-x', props.className)`). The dev might want to override `leading-x` here with the line-height in `text-xl`, so tailwind-merge needs to remove that.

But you can fix this by the way! You need to _remove_ a conflict from the config ([this one](https://github.com/dcastil/tailwind-merge/blob/v1.12.0/src/lib/default-config.ts#L1688)).

```ts
const twMerge = extendTailwindMerge({ /* your config */ }, config => {
    delete config.conflictingClassGroups['font-size']
    return config
})
```

**Comment by brandonmcconnell** [comment]
@dcastil Thanks!

**Comment by dcastil** [comment]
@brandonmcconnell I'm closing this issue as resolved. Let me know if your issue persists. 😊

**Comment by brandonmcconnell** [comment]
@dcastil Just wanted to confirm— using `delete config.conflictingClassGroups['font-size']` will still remove conflicting `font-size` utilities of the same type, correct? For exmaple, `twMerge('text-lg text-sm')` would still compile to `text-sm`, right?

**Comment by dcastil** [comment]
Yes! `config.conflictingClassGroups['font-size']` only holds the information that font-size classes clash with line-height classes. Classes from the same [group](https://github.com/dcastil/tailwind-merge/blob/v1.12.0/src/lib/default-config.ts#L121) always conflict with each other.

**Comment by brandonmcconnell** [comment]
@dcastil Awesome, thanks!

**Comment by dcastil** [comment]
Mentioned this issue in https://github.com/dcastil/tailwind-merge/discussions/226#discussioncomment-5917498.

**Comment by mrienstra** [comment]
Simple transformer which spits something out on the `console` (`process.env.NODE_ENV === "development"` only) when a class is dropped.

```ts
import clsx, { type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

const getCaller = () => {
  const getErrorObject = () => {
    try {
      throw Error("");
    } catch (err) {
      return err as Error;
    }
  };

  const err = getErrorObject();
  const caller_line = err?.stack?.split("\n")[4];
  const clean = caller_line?.trim().replace(/^at /, "from ");
  return clean;
};

const missingWords = (before: string, after: string) => {
  const afterArr = after.split(" ");
  return before
    .split(" ")
    .filter((w) => !afterArr.includes(w))
    .join(" ");
};

const twM = (...inputs: ClassValue[]) => {
  const joinedClasses = clsx(...inputs);
  const mergedClasses = twMerge(joinedClasses);
  if (
    process.env.NODE_ENV === "development" &&
    joinedClasses !== mergedClasses
  ) {
    console.log(
      `twM: "${joinedClasses}" lost "${missingWords(
        joinedClasses,
        mergedClasses
      )}"
      ${getCaller() || ""}`
    );
  }

  return mergedClasses;
};

export default twM;
```

Sample output:
```text
twM: "z-10 leading-relaxed text-9xl font-bold uppercase" lost "leading-relaxed"
      from Home (webpack-internal:///./src/pages/index.tsx:72:111)
```
