### ISSUE TITLE
Custom box shadow is removed, if box shadow color also set

### ISSUE THREAD

**Issue by andrey779evseev** [dcastil/tailwind-merge#225]
This only works with extended box shadows in tailwindcss config, default shadows merged correctly.

```tailwind.config.js
/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      boxShadow: {
        border: "0 0 0 1px",
      },
    },
    colors: {
      blue: "rgb(59, 73, 223)",
    },
  },
  plugins: [],
};
```

### Example with custom shadow and pure tailwind
`<div className="shadow-border shadow-blue">test</div>` 
*compiled* -> `<div class="shadow-border shadow-blue">test</div>`

### Example with custom shadow and tailwind with merge
`<div className={twMerge("shadow-border shadow-blue")}>test</div>`
*compiled* -> `<div class="shadow-blue">test</div>`
**( class `shadow-border` was removed )**

I'm not sure this is correct because, the same but with one of default shadows work differently

### Example with default shadow
this code
`<div className="shadow shadow-blue">test</div>`
the same like this 
`<div className={twMerge("shadow shadow-blue")}>test</div>`
*compiled* -> `<div class="shadow shadow-blue">sdfgs</div>`

[sandbox](https://codesandbox.io/p/sandbox/bold-grass-ju9kln)

**Comment by dcastil** [comment]
Hey @andrey779evseev and @mohamedGamalAbuGalala! 👋 

If you extend your Tailwind config with custom values, you need to configure tailwind-merge accordingly. Here is a guide for this: https://github.com/dcastil/tailwind-merge/blob/v1.12.0/docs/recipes.md#adding-custom-scale-from-tailwind-config-to-tailwind-merge-config

**Comment by andrey779evseev** [comment]
@dcastil Oh big thanks, sorry for stupid question

**Comment by dcastil** [comment]
No worries. 😊

**Comment by mohamedGamalAbuGalala** [comment]
@dcastil Can you help [with this](https://github.com/dcastil/tailwind-merge/discussions/226)?

**Comment by dcastil** [comment]
@mohamedGamalAbuGalala I get notifications for newly created discussions, no need to post about it here. 😊
