### ISSUE TITLE
Tailwind merge didn't merge custom value with only 0 unit

### ISSUE THREAD

**Issue by giovannetti-eric** [dcastil/tailwind-merge#234]
If I use a custom CSS value this way: `min-h-[0]` tailwind generated as intended a CSS property `min-height: 0;`

But when I use Tailwind merge like that, both Tailwind classes are keeped:
`twMerge("min-h-[1rem]", "min-h-[0]")` generate `"min-h-[1rem] min-h-[0]"`

I have to write it with a unit to make the merge to work:
`twMerge("min-h-[1rem]", "min-h-[0rem]")` generate `"min-h-[0rem]"`

**Comment by dcastil** [comment]
Thanks for reporting this! Will fix this later today.
