### ISSUE TITLE
Add Simon's video to docs

### ISSUE THREAD

**Issue by dcastil** [dcastil/tailwind-merge#236]
@simonswiss created a really good YouTube video explaining tailwind-merge. https://www.youtube.com/watch?v=tfgLd5ZSNPc

I should add it to the docs, it's especially valuable as an alternative learning mode to reading text for people who just stumbled upon the package. Probably fits in best in https://github.com/dcastil/tailwind-merge/blob/v1.12.0/docs/what-is-it-for.md.

**Comment by dcastil** [comment]
There is a nice thumbnail for the video in this Tweet: https://twitter.com/simonswiss/status/1663714686557360128

@simonswiss is it okay if I use the image in the tailwind-merge docs? If so, maybe you even have it in better image quality than what I can get from Twitter?

**Comment by dcastil** [comment]
Also just realized I could use https://img.youtube.com/vi/tfgLd5ZSNPc/maxresdefault.jpg and this Markdown:

```md
[![The "why" behind tailwind-merge](https://img.youtube.com/vi/tfgLd5ZSNPc/maxresdefault.jpg)](https://www.youtube.com/watch?v=tfgLd5ZSNPc)
```

rendered it looks like this:

[![The "why" behind tailwind-merge](https://img.youtube.com/vi/tfgLd5ZSNPc/maxresdefault.jpg)](https://www.youtube.com/watch?v=tfgLd5ZSNPc)

**Comment by simonswiss** [comment]
Yeah forcl sure - go ahead, happy for you to use this thumbnail.

Looks like you've got it worked out!
