### ISSUE TITLE
col-span- classes not being merged

### ISSUE THREAD

**Issue by edwin177** [dcastil/tailwind-merge#265]
### Describe the bug

`twMerge('col-span-full', 'col-span-1')` outputs `col-span-full col-span-1` instead of `col-span-1`

### Environment

```
"tailwind-merge": "1.13.2",
"tailwindcss": "3.3.2",
```

**Comment by dcastil** [comment]
Hey @edwin177! 👋

Thanks for reporting. I'll fix this.

**Comment by edwin177** [comment]
Ah, thanks for handling this so quickly. I did a search for `col-span` in the repo and didn't find anything, so I didn't realize the bug was specific to `col-span-full`.
