### ISSUE TITLE
There is a big issue here.

### ISSUE THREAD

**Issue by abdulbasit-94** [dcastil/tailwind-merge#27]
tailwin-merge('text-sm text-bold', 'text-red' , 'text-semibold text-lg', 'text-blue');
 
 this is not gonna work fine.  only one text- will work when we run this and this will also not override classes.

**Comment by dcastil** [comment]
Hey @abdulbasit-94! If I understand it correctly, you concern is that tailwind-merge will merge the classes from your example incorrectly and will only output `text-blue`. If that's the case, I got you covered. 😄

tailwind-merge has a mechanism to differentiate between different class groups. It knows that `text-sm` and `text-lg` belong to one class group and `text-red` and `text-blue` to another one.

So this is the behavior you'll get:

```ts
import { twMerge } from 'tailwind-merge'

twMerge('text-sm text-bold', 'text-red' , 'text-semibold text-lg', 'text-blue')
// → 'text-lg text-blue'

// `text-bold` and `text-semibold` are not in the default config of Tailwind, so tailwind-merge
// assumes these are color classes and removes them in favor of `text-blue`.
// Here is the result of using `font-bold` and `font-semibold` which are in the default config.
twMerge('text-sm font-bold', 'text-red' , 'font-semibold text-lg', 'text-blue')
// → 'font-semibold text-lg text-blue'
```

You can check this out here and play around with the code. 👉 https://codesandbox.io/s/dcastil-tailwind-merge-24-medi4?file=/src/index.ts

I'll close this issue for now. Feel free to tell me if I misunderstood you and I'll reopen it.
