### ISSUE TITLE
twMerge is removing custom classes wrongly

### ISSUE THREAD

**Issue by sumanthyedoti** [dcastil/tailwind-merge#276]
- I have `text-40` defined is tailwind config as `2.5rem`
- Had the class by default to a button
- `twMerge` is removing the classes. I had to pass the classes explicitly, `Button className="text-40"`, 
    - 👉 then other custom class `text-white-light` got removed

Are the custom classes conflicting because they start with `text-`? 

Note: I am using `classnames` library
config:
```js
theme: {
  expand: {
      fontSize: {
        //...
        '40': '2.5rem',
      },
  }
}
```

**Comment by sumanthyedoti** [comment]
Thanks @dcastil

**Comment by dcastil** [comment]
Closing this issue. Please let me know if your issue isn't resolved and I should reopen it.
