### ISSUE TITLE
Can't import the named export 'createClassUtils' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by luminajames** [dcastil/tailwind-merge#282]
Hi,

I have a Typescript React app which is bundled with Craco. I'm trying to use `tailwind-merge` but whenever I try to compile it fails with this error message:

```
Failed to compile.


./node_modules/tailwind-merge/dist/lib/config-utils.mjs
Can't import the named export 'createClassUtils' from non EcmaScript module (only default export is available)
```

I have tried installing version 1.13.0 and 1.14.0 of `tailwind-merge` with no luck. I've also deleted `node_modules` so that I can reinstall dependencies with `npm i`.

If I open `config-utils.mjs`, I can see the import that the error is describing:
```
import { createClassUtils } from './class-utils.mjs';
```
But if I navigate to this file myself, I can see a named export only. So not sure what is causing this issue:
```
export { createClassMap, createClassUtils };
```

### To Reproduce

I can provide a reproducible example if it will help. But I was wondering if there's anything I can check first.

### Environment

- `tailwind-merge@1.14.0` (also tried @1.13.0)
- `@craco/craco@6.4.5`
- `tailwindcss@npm:@tailwindcss/postcss7-compat@^2.2.17`
- `typescript@4.9.5`

**Comment by luminajames** [comment]
Hi @dcastil,

I thought it was likely something on my end, but wanted to ask either way. Do you know which Craco setting might be causing this issue? Fine if you don't, I'm just confused around what's going on. I've experienced something similar with Rollup for a React component library that I maintain. It will say that something is not default exported when I can see that it is.

**Comment by dcastil** [comment]
I didn't use Craco so far and also never saw this error before, so unfortunately I won't be able to help.

I think I'd try to pull things out of the config until I see a change in behavior, maybe this way you'll find out where the problem lies.

**Comment by luminajames** [comment]
> I didn't use Craco so far and also never saw this error before, so unfortunately I won't be able to help.
> 
> I think I'd try to pull things out of the config until I see a change in behavior, maybe this way you'll find out where the problem lies.

Alright, I'll keep researching. Thanks for your help and the work you do on `tailwind-merge`.
