### ISSUE TITLE
touch classes incorrectly override eachother

### ISSUE THREAD

**Issue by jamesbirtles** [dcastil/tailwind-merge#312]
### Describe the bug

When trying to use, for example, `touch-pan-y touch-pinch-zoom`, twMerge will remove the touch-pan-y. 

### To Reproduce

`twMerge("touch-pan-y touch-pinch-zoom")`

### Expected behavior

Looking at the css, some of the `touch-` classes can be applied together
<img width="648" alt="CleanShot 2023-09-12 at 16 49 14@2x" src="https://github.com/dcastil/tailwind-merge/assets/3743418/adcd3b95-dfab-4e3b-aa4c-9a1ce53f5b12">
<img width="622" alt="CleanShot 2023-09-12 at 16 49 55@2x" src="https://github.com/dcastil/tailwind-merge/assets/3743418/11f79817-f8a9-4a35-b61c-11aeb7877d33">

So the touch-pan-y should be kept alongside the touch-pinch-zoom

### Environment

-   tailwind-merge version: 1.14.0

**Comment by dcastil** [comment]
Hey @jamesbirtles! 👋

Thanks for reporting!

You're right. Just took a look in the Tailwind source code and found this: https://github.com/tailwindlabs/tailwindcss/blob/42e75ba4b860ef75656cff3119aa56e70714d34c/src/corePlugins.js#L969-L1018

The x, y and pinch-zoom classes need to go into separate groups so they can be used together.

I'm currently working on a v2 release and will include this fix in there. This means you'll need a major version upgrade to get this. I hope this is fine.

PS: Thanks for your patience, I'm just coming back from a vacation.
