### ISSUE TITLE
Properly strict `classGroups` keys

### ISSUE THREAD

**Issue by KajSzy** [dcastil/tailwind-merge#314]
### Describe the bug

Using `extendTailwindMerge` I've to check source code to see proper `classGroups` keys to properly handle custom classes.

### To Reproduce

```ts

const twMerge = extendTailwindMerge({
  classGroups: {
    // here keys should be defined as strict 
    'min-h': [{ 'min-h': ['page'] }],
  },
});

```

### Expected behavior

Types for `classGroups`, `conflictingClassGroups` and `conflictingClassGroupModifiers` should properly strict keys.

### Environment

-   tailwind-merge version: [e.g. 1.14.0]

### Additional context

type `ClassGroupId` should be an union of all keys that I can found [here](https://github.com/dcastil/tailwind-merge/blob/v1.13.1/src/lib/default-config.ts#L121)

**Comment by dcastil** [comment]
Hey @KajSzy! 👋

Good news, [this is already done](https://github.com/dcastil/tailwind-merge/pull/279) and will be released in an upcoming [v2 release](https://github.com/dcastil/tailwind-merge/milestone/1).

I'm closing this issue, let me know if this doesn't solve your problem.
