### ISSUE TITLE
bug on build NextJs

### ISSUE THREAD

**Issue by mehranMinaei** [dcastil/tailwind-merge#325]
Failed to compile.

./node_modules/tailwind-merge/dist/index.d.ts:7:23
Type error: ',' expected.

   5 | export { fromTheme } from './lib/from-theme';
   6 | export { mergeConfigs } from './lib/merge-configs';
>  7 | export { twJoin, type ClassNameValue } from './lib/tw-join';

error ClassNameValue

**Comment by dcastil** [comment]
Hey @mehranMinaei! 👋

Could you create a minimal example (e.g. a public repo on GitHub) so I can reproduce the bug?

**Comment by mehranMinaei** [comment]
Hi, problem solved, in tsconfig.json the field contained this "**/*.js", I removed this and then everything was ok.
Thank

**Comment by dcastil** [comment]
Alright, gonna close this issue then. 😊
