### ISSUE TITLE
Conflict between text size and text color

### ISSUE THREAD

**Issue by plckr** [dcastil/tailwind-merge#326]
### Describe the bug

I'm trying to apply two different classes, one for text color and another for text size, but tw-merge removes one of them assuming they have the same purpose.

### To Reproduce

I have the following tailwind config 
```
module.exports = {
  ...
  theme: {
    fontSize: ({ theme }) => ({
      xxs: '.625rem',
    }),
    colors: {
      "ig-text-primary-invert": "#fff"
    }
  }
}
```

and the tw-merge function
`twMerge('text-ig-text-primary-invert text-xxs')`
returns the last

and running the opposite way
`twMerge('text-xxs text-ig-text-primary-invert')`
returns the other class

### Expected behavior

Should keep both instead of assuming they are equal purpose. One is for `color` and the other for `fontSize`

### Environment

-   tailwind-merge version: 1.14.0

**Comment by G9000** [comment]
same issue with me, and we use in production. Really need this fix :<

**Comment by plckr** [comment]
> same issue with me, and we use in production. Really need this fix :< or sorted
> 
> edit. Need to declare and extend the fontSize only. color not needed

Even with extending the fontSize doesn't work either
```
module.exports = {
  ...
  theme: {
    colors: {
      "ig-text-primary-invert": "#fff"
    }
  },
  extend: {
    fontSize: {
      xxs: '.625rem',
    },
  }
}
```

**Comment by G9000** [comment]
> > same issue with me, and we use in production. Really need this fix :< or sorted
> > edit. Need to declare and extend the fontSize only. color not needed
> 
> Even with extending the fontSize doesn't work either
> 
> ```
> module.exports = {
>   ...
>   theme: {
>     colors: {
>       "ig-text-primary-invert": "#fff"
>     }
>   },
>   extend: {
>     fontSize: {
>       xxs: '.625rem',
>     },
>   }
> }
> ```
> 
> the result is the same

have you extend TailwindMerge config?

```typescript
const customTwMerge = extendTailwindMerge({
    theme: {
        'font-size': [{ text: ['xxs'] }],
    },
})
```

**Comment by plckr** [comment]
> > > same issue with me, and we use in production. Really need this fix :< or sorted
> > > edit. Need to declare and extend the fontSize only. color not needed
> > 
> > 
> > Even with extending the fontSize doesn't work either
> > ```
> > module.exports = {
> >   ...
> >   theme: {
> >     colors: {
> >       "ig-text-primary-invert": "#fff"
> >     }
> >   },
> >   extend: {
> >     fontSize: {
> >       xxs: '.625rem',
> >     },
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the result is the same
> 
> have you extend TailwindMerge config?
> 
> ```ts
> const customTwMerge = extendTailwindMerge({
>     classGroups: {
>         'font-size': [{ text: ['xxs'] }],
>     },
> })
> ```

Indeed it worked, thanks.
Anyways, the library should handle it automatically, do you agree?

**Comment by dcastil** [comment]
Hey @plckr! 👋

@G9000 is right, tailwind-merge unfortunately can't access your `tailwind.config.js` because it isn't part of your build system.

By the way, if you use the key `2xs` instead of `xxs` you don't need to configure anything since tailwind-merge detects classes like `text-[number]xs` as a font-size class automatically. Basically the same like `text-2xl`, just into the other direction. 😁

@G9000 thanks for help! 🙏

**Comment by plckr** [comment]
@dcastil that's sad tw-merge can't access tailwind config, it would be very helpful. Do you think there's a way in the future?

**Comment by dcastil** [comment]
I'm closing this issue, there is unfortunately no immediate resolution to reading the `tailwind.config.js` file. Let me know if I should reopen again.

**Comment by yap-qliro** [comment]
```ts
const twMerge = extendTailwindMerge({
  override: {
    classGroups: {
      "font-size": [
        {
          text: [
            "xxs",
          ],
        },
      ],
    },
  },
});
