### ISSUE TITLE
Broken link in v2 release

### ISSUE THREAD

**Issue by theskillwithin** [dcastil/tailwind-merge#330]
reading the v2 release (https://github.com/dcastil/tailwind-merge/releases/tag/v2.0.0) points to a link https://github.com/dcastil/tailwind-merge/blob/v2.0.0/v1-to-v2-migration.md which appears not to work

**Comment by dcastil** [comment]
Oh, thanks for letting me know! Fixed it in the release.

**Comment by dcastil** [comment]
The migration guide is here by the way 😁

https://github.com/dcastil/tailwind-merge/blob/v2.0.0/docs/changelog/v1-to-v2-migration.md
