### ISSUE TITLE
Module '"tailwind-merge"' declares 'ClassValidator' locally, but it is not exported.

### ISSUE THREAD

**Issue by xsjcTony** [dcastil/tailwind-merge#331]
### Describe the bug

`ClassValidator` type is exported in source code, but not in the dist build `dts` file

### To Reproduce

`import type { ClassValidator } from 'tailwind-merge';`

### Expected behavior

It should export

### Environment

-   tailwind-merge version: latest (v2.0.0)

**Comment by dcastil** [comment]
Hey @xsjcTony! 👋

The `ClassValidator` type is used internally but it isn't exported from the package. You can see all the package exports here: https://github.com/dcastil/tailwind-merge/blob/v2.0.0/src/index.ts

The type is really simple and you can recreate it in your own codebase if you want:

```ts
type ClassValidator = (classPart: string) => boolean
```

**Comment by xsjcTony** [comment]
Yep that's true. But

1. It's a bit weird that the type is exported in the source code but not in the build file
2. I'd still prefer relying on types exported from the package instead of defining my own, although it's simple but I won't know if one day it changed

**Comment by dcastil** [comment]
That makes sense, although that would of course only happen in a major release. I'll add the type to the library exports in the next release.
