### ISSUE TITLE
Congrats on getting married!

### ISSUE THREAD

**Issue by jessekrubin** [dcastil/tailwind-merge#332]
No bug. 

Congrats on getting married!

**Comment by dcastil** [comment]
Haha best issue ever. Thank you! 😆

**Comment by dcastil** [comment]
Closing this since I accepted the congrats. 😁

**Comment by jessekrubin** [comment]
@dcastil hoping this "issue" isn't "resolved"/"fixed" (ie wishing you and your partner all the best!)

**Comment by dcastil** [comment]
Definitely not! Here is a recent picture of us by the way (at the wedding of a friend of us).

![IMG_1186](https://github.com/dcastil/tailwind-merge/assets/31006608/ac784e87-5da6-4bc2-9b15-8da7998feb9d)
