### ISSUE TITLE
Incorrect typing in extendTailwindMerge

### ISSUE THREAD

**Issue by plckr** [dcastil/tailwind-merge#339]
### Describe the bug

I just upgraded to version 2.0.0 and I'm extending the config and the config works great when I add an array to the classGroups, but it is against the types already defined.

### To Reproduce

```js
const customTwMerge = extendTailwindMerge({
  override: {},
  extend: {
    classGroups: {
      'max-w': ['modal', 'container']
    }
  }
});

console.log(customTwMerge('max-w-modal max-w-container'));
// output max-w-modal max-w-container
```

### Expected behavior

Should output only `max-w-container`
If you wrap the classGroups in an array it works great, but types are incorrect.

### Environment

-   tailwind-merge version: 2.0.0

### Additional context

Typing error:
```
Type '{ 'max-w': string[]; }[]' is not assignable to type 'Partial<Record<DefaultClassGroupIds, ClassGroup<DefaultThemeGroupIds>>>'.
  Types of property 'fill' are incompatible.
    Type '(value: { 'max-w': string[]; }, start?: number | undefined, end?: number | undefined) => { 'max-w': string[]; }[]' is not assignable to type 'readonly ClassDefinition<DefaultThemeGroupIds>[]'.
```

**Comment by dcastil** [comment]
Hey @plckr! 👋

You forgot to add the prefix to your classes. You can do that in one of two ways:

```ts
'max-w': ['max-w-modal', 'max-w-container']
```

```ts
'max-w': [{ 'max-w': ['modal', 'container'] }]
```

**Comment by plckr** [comment]
@dcastil thank you for the fast response!
Indeed you're right, thanks so much!

I find it a bit confusing the docs

**Comment by dcastil** [comment]
Yeah, I need to improve that. It doesn't help that I picked keys that are often the same as the prefixes. 😅

**Comment by plckr** [comment]
Keep up the great work! Thank you!
