### ISSUE TITLE
Building issues

### ISSUE THREAD

**Issue by PadowYT2** [dcastil/tailwind-merge#341]
### Describe the bug

With the release of 2.0.0, I'm not able to build with webpack:
```
ERROR in ./node_modules/tailwind-merge/dist/bundle-cjs.js 49:30
Module parse failed: Unexpected token (49:30)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   return classPartObject.validators.find(({
|     validator
>   }) => validator(classRest))?.classGroupId;
| }
| const arbitraryPropertyRegex = /^\[(.+)\]$/;
 @ ./node_modules/@vertisanpro/flowbite-react/lib/esm/components/Sidebar/SidebarLogo.js 21:0-41 44:15-22
 @ ./node_modules/@vertisanpro/flowbite-react/lib/esm/components/Sidebar/index.js
 @ ./node_modules/@vertisanpro/flowbite-react/lib/esm/index.js
 @ ./resources/scripts/components/App.tsx
 @ ./resources/scripts/index.tsx
 @ multi react-hot-loader/patch ./resources/scripts/index.tsx
```

I have a fork of `flowbite-react` called `@vertisanpro/flowbite-react`, when I change the tailwind-merge version to 1.14.0, it works perfectly fine

### To Reproduce

1. Use webpack
2. Use tailwind-merge@2.0.0

### Expected behavior

It should build fine

### Environment

- tailwind-merge@2.0.0
- react@16.14.0

**Comment by dcastil** [comment]
Hey @PadowYT2! 👋

Looks like your bundler doesn't recognize optional chaining. You can use the ES5 build of tailwind-merge to use a code path without the optional chaining syntax in it.

For that, use this import instead:

```js
import { twMerge } from 'tailwind-merge/es5'
```

**Comment by PadowYT2** [comment]
> Hey @PadowYT2! 👋
> 
> Looks like your bundler doesn't recognize optional chaining. You can use the ES5 build of tailwind-merge to use a code path without the optional chaining syntax in it.
> 
> For that, use this import instead:
> 
> ```js
> import { twMerge } from 'tailwind-merge/es5'
> ```

I suspect there will be no other fixes? If so, alright I'll modify my fork to use ES5

**Comment by dcastil** [comment]
Do you have a better fix in mind? 🤔 I don't want to use ES5 for the default bundle because it makes the bundle larger while most people don't need the bundle compiled down to ES5. Providing two entry points seems to be the best of both worlds since everyone can choose the bundle they need.

**Comment by PadowYT2** [comment]
> Do you have a better fix in mind? 🤔 I don't want to use ES5 for the default bundle because it makes the bundle larger while most people don't need the bundle compiled down to ES5. Providing two entry points seems to be the best of both worlds since everyone can choose the bundle they need.

No problem then, I'll just use what you suggested, thanks, have a good day

**Comment by PadowYT2** [comment]
> ```js
> tailwind-merge/es5
> ```

Hey, haven't really updated to v2, now that I did, `tailwind-merge/es5` seems to not exist - "Cannot find module 'tailwind-merge/es5' or its corresponding type declarations."

**Comment by PadowYT2** [comment]
Hey, haven't really updated to v2, now that I did, `tailwind-merge/es5` seems to not exist - "Cannot find module 'tailwind-merge/es5' or its corresponding type declarations."

**Comment by dcastil** [comment]
@PadowYT2 Oh that's weird. The types are defined [here](https://github.com/dcastil/tailwind-merge/blob/v2.0.0/package.json#L39) and when I use the `tailwind-merge/es5` bundle in a Vite project of mine using TypeScript, it also gets the types right. Are you sure that your module resolution system is set up correctly? Can you make a reproduction repo so I can take a look?

**Comment by PadowYT2** [comment]
> @PadowYT2 Oh that's weird. The types for the `tailwind-merge/es5` bundle are defined [here](https://github.com/dcastil/tailwind-merge/blob/v2.0.0/package.json#L39) and when I use the bundle in a Vite project of mine using TypeScript, it also gets the types right. Are you sure that your module resolution system is set up correctly? Can you make a reproduction repo so I can take a look?

Hello, sorry for not responding for a long time. You can see the project on [VertisanPRO/flowbite-react](https://github.com/VertisanPRO/flowbite-react). Currently there's no commit with the es5 version, but basically, I update tailwind-merge to v2 and edit like this
```diff
- import { twMerge } from 'tailwind-merge';
+ import { twMerge } from 'tailwind-merge/es5';
```

and VSCode complains with "Cannot find module 'tailwind-merge/es5' or its corresponding type declarations."

**Comment by dcastil** [comment]
@PadowYT2 just looked into it and the issue is that you have your TypeScript `moduleResolution` set to `node` [here](https://github.com/VertisanPRO/flowbite-react/blob/91e417c6997bfab9a09fdf07f2a49cc9df13d1a9/tsconfig.json#L12) which is outdated and doesn't know about the `exports` field. [Here](https://www.typescriptlang.org/docs/handbook/modules/theory.html#:~:text=node10%3A%20Formerly%20known%20as%20node) is some documentation on that.

You need to set the field to `node16`, `nodenext` or `bundler`, then TypeScript can resolve the module correctly.

**Comment by PadowYT2** [comment]
> @PadowYT2 just looked into it and the issue is that you have your TypeScript `moduleResolution` set to `node` [here](https://github.com/VertisanPRO/flowbite-react/blob/91e417c6997bfab9a09fdf07f2a49cc9df13d1a9/tsconfig.json#L12) which is outdated and doesn't know about the `exports` field. [Here](https://www.typescriptlang.org/docs/handbook/modules/theory.html#:~:text=node10%3A%20Formerly%20known%20as%20node) is some documentation on that.
> 
> You need to set the field to `node16`, `nodenext` or `bundler`, then TypeScript can resolve the module correctly.

Only now I could do something about it. Anyways I cannot do that unfortunately, I have forked the project as I only see this as a solution - [VertisanPRO/tailwind-merge](https://github.com/VertisanPRO/tailwind-merge). But still thank you!
