### ISSUE TITLE
Display class not being removed when it precedes `line-clamp-*`

### ISSUE THREAD

**Issue by Aleuck** [dcastil/tailwind-merge#345]
### Describe the bug

The `line-clamp-*` depends on having display set to `-webkit-box` or `-webkit-inline-box`. Tailwind `line-clamp-*` sets `display: -webkit-box`.

Therefore there is no point in keeping other basic display classes like `inline`, `block` or `inline-block` when there is a `line-clamp-*` afterwards.

However, `twMerge` keeps Display classes when they are followed by a line clamp class.

### To Reproduce

```js
> twMerge('inline-block', 'line-clamp-1')
'inline-block line-clamp-1'
> twMerge('inline', 'line-clamp-2')
'inline line-clamp-2'
> twMerge('block', 'line-clamp-2')
'block line-clamp-2'
```

### Expected behavior

```js
> twMerge('inline-block', 'line-clamp-1')
'line-clamp-1'
> twMerge('inline', 'line-clamp-2')
'line-clamp-2'
> twMerge('block', 'line-clamp-2')
'line-clamp-2'
```

### Environment

-   tailwind-merge version: 2.0.0

**Comment by dcastil** [comment]
Hey @Aleuck! 👋

You're right. Tailwind also sets `overflow: hidden` in the line-clamp classes, so that one should be removed, too. I'll fix this in the coming days.

**Comment by dcastil** [comment]
@agauravdev if you want `md:block` to be removed as well, then you'll need to use `line-clamp-2 md:line-clamp-2`. Not pretty though.
