### ISSUE TITLE
Vercel Deploy Build Failed Type error: ',' expected

### ISSUE THREAD

**Issue by sridharvvt** [dcastil/tailwind-merge#356]
### Describe the bug

![image](https://github.com/dcastil/tailwind-merge/assets/146917451/9fdfa802-38ce-4648-ad2f-94bd9e2c1391)

build failed Type error: ',' expected.

### Expected behavior

removing the type can solve the issue on the local but on vercel build was failing

### Environment

- "next": "^12.1.5",
- "tailwind-merge": "^2.1.0",
- "typescript": "4.4.4"

**Comment by dcastil** [comment]
Hey @sridharvvt! 👋

Looks like your TypeScript version is quite old and doesn't support the `type` keyword in exports. Did you try to upgrade your TypeScript?

**Comment by dcastil** [comment]
Closing this as stale
