### ISSUE TITLE
Wrong merge of stroke classes

### ISSUE THREAD

**Issue by alesji** [dcastil/tailwind-merge#370]
### Describe the bug

When using arbitrary values for stroke width and color, it doesnt work properly
`"stroke-[hsl(350_80%_0%)]","stroke-[10px]"` will result in only `stroke-[10px]` to be left behind, but thats not correct, both should be kept, since tailwind differentiates between using size unit and color unit by creating stroke-width: for size unit and stroke: for color, tailwind merge incorrectly takes it as colliding classes

### Expected behavior
keep both color and size arbitrary value classes

**Comment by dcastil** [comment]
Hey @alesji! I could reproduce it and will fix this in the coming days.

**Comment by alesji** [comment]
> Hey @alesji! I could reproduce it and will fix this in the coming days.

Awesome, thanks
