### ISSUE TITLE
Replace Bundlephobia links since it seems to be dead

### ISSUE THREAD

**Issue by dcastil** [dcastil/tailwind-merge#397]
> Bundlephobia resource seems to be dead, since the end of 2023 😮‍💨 
> We should replace a link, for example with https://bundlejs.com/?q=tailwind-merge

_Originally posted by @ivan-kleshnin in https://github.com/dcastil/tailwind-merge/discussions/185#discussioncomment-8901594_

**Comment by dcastil** [comment]
Related:
- https://github.com/pastelsky/bundlephobia/issues/863
- https://github.com/pastelsky/bundlephobia/issues/857
- https://github.com/pastelsky/bundlephobia/issues/842
- https://github.com/pastelsky/bundlephobia/issues/798
- https://github.com/pastelsky/bundlephobia/issues/796

**Comment by dcastil** [comment]
I'm not 100% convinced of https://bundlejs.com since it's not immediately obvious how to get bundle size info. Would be nice if there was a service which immediately displayed the library size and ideally even the size of each exported variable like Bundlephobia used to do it.

**Comment by ivan-kleshnin** [comment]
Right. I guess you could add it with a badge:

<img class="inline-block" src="https://deno.bundlejs.com/?q=tailwind-merge&amp;badge" alt="tailwind-merge">

**Comment by dcastil** [comment]
Not sure when it happened, but Bundlephobia works again. I'll close this issue until the problem reappears.

**Comment by ivan-kleshnin** [comment]
Yes, it's luckily back.
