### ISSUE TITLE
`bg` merges ok, but `color` doesnt

### ISSUE THREAD

**Issue by pvinis** [dcastil/tailwind-merge#407]
### Describe the bug

I am using twmerge and `color` is not merging right.

### To Reproduce

https://github.com/dcastil/tailwind-merge/pull/406

### Expected behavior

With `twMerge('color-red-500 color-black')` I would expect the result to be `color-black`.

### Environment

-   tailwind-merge version: 2.3.0

**Comment by dcastil** [comment]
Hey @pvinis! 👋

That is because `color-black` is not a Tailwind CSS class, at least not in the default config. I think you meant `text-black` which modifies the CSS property `color`, right? https://tailwindcss.com/docs/text-color

**Comment by pvinis** [comment]
OH. MYGOD.

Closing everything, I'm sorry, I was confused and I can't believe I mixed these up 🙈.

Thank you for your work!

**Comment by dcastil** [comment]
Haha no worries! 😁 Happy to help!
