### ISSUE TITLE
Add GitHub Action that adds `context-v2` label everywhere

### ISSUE THREAD

**Issue by dcastil** [dcastil/tailwind-merge#432]
I'm putting the `context-v2` label on every new issue, discussion and PR manually to mark it as having been created in the context of tailwind-merge v2. Would be nice to build a GitHub action that does this automatically whenever a new issue, discussion or PR is created in this repository.

Here are the docs for GitHub Actions: https://docs.github.com/en/actions
And here is the workflow syntax explained: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

If anyone wants to pick it up, I'm accepting PRs for this and also happy to help if needed. 😊

**Comment by Pritam1211** [comment]
Hi @dcastil,
I have created the `context-v2-label ` branch and added the github action file to that branch. Now how can I test this action?
Can you help me
