### ISSUE TITLE
cursor-not-allowed not merge

### ISSUE THREAD

**Issue by WangJM001** [dcastil/tailwind-merge#438]
### Describe the bug

cursor-not-allowed not merge

### To Reproduce

```js
twMerge('cursor-pointer', 'cursor-not-allowed')
```

### Expected behavior

Expected：class='cursor-not-allowed';

Actual: class='cursor-pointer cursor-not-allowed';

### Environment

tailwind-merge version: [2.3.0]

**Comment by dcastil** [comment]
Hey @WangJM001! 👋

Just checked and both `cursor-pointer` and `cursor-not-allowed` are defined in the default config here: https://github.com/dcastil/tailwind-merge/blob/v2.3.0/src/lib/default-config.ts#L1513-L1559

Did you configure `twMerge` in any way? Or are you using Vue?

**Comment by WangJM001** [comment]
Ignore, I made a mistake

**Comment by dcastil** [comment]
Ah alright. 😁

**Comment by WangJM001** [comment]
Sorry，thanks for such a quick answer.😊
