### ISSUE TITLE
Why is leading not output?

### ISSUE THREAD

**Issue by lmsccc** [dcastil/tailwind-merge#446]
### Describe the bug

console.log(twMerge("text-white leading-[20px]", "text-[14px] font-[600]")) // output is "text-white text-[14px] font-[600]"

### To Reproduce

https://codesandbox.io/p/sandbox/modest-darkness-lnzfvt?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clypbfvpy00063b6kw6uk9z48%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clypbfvpy00023b6k96g70enf%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clypbfvpy00033b6kkvf3nibj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clypbfvpy00053b6kwc4abgs7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B76.07939727615184%252C23.920602723848162%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clypbfvpy00023b6k96g70enf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clypbfvpy00013b6k80sriw20%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clypfw5d3003j3b6kwhoi5tv6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A11%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A11%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clypbfvpy00023b6k96g70enf%2522%252C%2522activeTabId%2522%253A%2522clypfw5d3003j3b6kwhoi5tv6%2522%257D%252C%2522clypbfvpy00053b6kwc4abgs7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clypbfvpy00043b6kt50hurco%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clypbfvpy00053b6kwc4abgs7%2522%252C%2522activeTabId%2522%253A%2522clypbfvpy00043b6kt50hurco%2522%257D%252C%2522clypbfvpy00033b6kkvf3nibj%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clypbfvpy00033b6kkvf3nibj%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Expected behavior

output is "text-white leading-[20px] text-[14px] font-[600] "

### Environment

-   tailwind-merge 2.4.0

**Comment by dcastil** [comment]
Hey @lmsccc! 👋

That is intended because font-size classes add a line-height CSS property, overriding line-height classes if you place it afterwards. If you want to change this overriding behavior and don't use line-heights in your font-size classes, you can override the conflict between the font-size and line-height classes:

```ts
import { extendTailwindMerge } from 'tailwind-merge'

const twMerge = extendTailwindMerge({
    override: {
        conflictingClassGroups: {
            // In the default config the value is ['leading']
            // See https://github.com/dcastil/tailwind-merge/blob/v2.4.0/src/lib/default-config.ts#L1777
            'font-size': []
        }
    }
})
```

---

Related: https://github.com/dcastil/tailwind-merge/issues/257, https://github.com/dcastil/tailwind-merge/issues/218, https://github.com/dcastil/tailwind-merge/issues/187, https://github.com/dcastil/tailwind-merge/issues/59

**Comment by lmsccc** [comment]
@dcastil Thanks!!!
