### ISSUE TITLE
Transition gradient not working

### ISSUE THREAD

**Issue by tiagobbraga** [dcastil/tailwind-merge#447]
### Describe the bug
Gradient transition does not work.

### To Reproduce

I applied these styles in a button:
`transition-all duration-250 ease-linear bg-gradient-to-r to-color-one via-color-one from-color-two bg-size-200 bg-pos-0 hover:bg-pos-100`

And too setted these extension in my tailwind.config.ts
```
...
backgroundSize: {
 "size-200": "200% 200%",
},
backgroundPosition: {
 "pos-0": "0% 0%",
 "pos-100": "100% 100%",
},
...
```

The button has these a default style
`inline-flex items-center justify-center whitespace-nowrap text-sm rounded-md font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50`

But the transition does not work.

### Expected behavior

E.g. Without merge:
[https://play.tailwindcss.com/XFQDCOKQ8L](https://play.tailwindcss.com/XFQDCOKQ8L)

### Environment

-   tailwind-merge version: [e.g. 2.4.0]

---

I removed the merge and so worked.

**Comment by dcastil** [comment]
Hey @tiagobbraga! 👋

tailwind-merge doesn't have access to the tailwind.config.ts file and you need to configure it separately so it knows about the text-button class.

Here is an example on how to configure tailwind-merge: https://github.com/dcastil/tailwind-merge/blob/v2.4.0/docs/recipes.md#adding-custom-scale-from-tailwind-config-to-tailwind-merge-config.

And here is the documentation on how the tailwind-merge configuration works: https://github.com/dcastil/tailwind-merge/blob/v2.4.0/docs/configuration.md#usage-with-custom-tailwind-config.

---

Related: https://github.com/dcastil/tailwind-merge/issues/368, https://github.com/dcastil/tailwind-merge/discussions/322, https://github.com/dcastil/tailwind-merge/issues/321, https://github.com/dcastil/tailwind-merge/discussions/315, https://github.com/dcastil/tailwind-merge/issues/302, https://github.com/dcastil/tailwind-merge/issues/276, https://github.com/dcastil/tailwind-merge/discussions/275, https://github.com/dcastil/tailwind-merge/issues/274, https://github.com/dcastil/tailwind-merge/issues/250, https://github.com/dcastil/tailwind-merge/issues/207

**Comment by tiagobbraga** [comment]
Thanks @dcastil!

**Comment by dcastil** [comment]
No problem! 😊 Let me know if you get stuck somewhere and feel free to close this issue in case your problem is resolved.

**Comment by dcastil** [comment]
Closing this one as resolved.

**Comment by muhammadfathurraiyan** [comment]
it's little bit tricky try this

```javascript
<button className={`transition-all duration-250 ease-linear bg-gradient-to-r to-color-one via-color-one from-color-two bg-size-200 bg-pos-0 hover:bg-pos-100 ${cn("inline-flex items-center justify-center whitespace-nowrap text-sm rounded-md font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50", className)}`}>{children}</button>
```
