### ISSUE TITLE
Multiline unsupported since v2.5.0

### ISSUE THREAD

**Issue by madmoizo** [dcastil/tailwind-merge#458]
### Describe the bug

Multiline does not work anymore. (no `\n` `\t` cleaning before processing?)

### To Reproduce

```js
twMerge(
	`
	justify-center
`,
	"justify-start"
)
```
Result:
```
			justify-center
		 justify-start
```

### Expected behavior

```
 justify-start
```

### Environment

-   tailwind-merge version: 2.5.0+

**Comment by dcastil** [comment]
Indeed, will fix this soon.
