### ISSUE TITLE
Missing class group for `items-X` (X = left | center | right)

### ISSUE THREAD

**Issue by xeger** [dcastil/tailwind-merge#464]
### Describe the bug

The class group for align-items is [specified in the Tailwind docs](https://tailwindcss.com/docs/align-items) as `items-left` and so on.

I can extend the base to compensate, which I have done, but I wanted to raise this issue as a possible bug.

### To Reproduce

```javascript
twMerge('items-left items-center') // => 'items-left items-center'
```

### Expected behavior

twMerge('items-left items-center') // => 'items-center'

### Environment

-   tailwind-merge version: 2.5.2

### Additional context

Looking in the default config, I see there is an `align-items` group, but this is either an alias that tailwind provides, or it's a downright bug in `tailwind-merge`. I do not see any mention of `align-items` in the Tailwind v3 docs.

**Comment by dcastil** [comment]
Hey @xeger! 👋

I think you meant `items-start`, right? The class `items-left` doesn't exist in Tailwind CSS and therefore gets ignored by tailwind-merge. You can find the tailwind-merge config for the align-items group here: https://github.com/dcastil/tailwind-merge/blob/v2.5.2/src/lib/default-config.ts#L441-L445

**Comment by xeger** [comment]
Right you are! 🫡 Thanks again for this excellent tool.
