### ISSUE TITLE
merge rounded error!

### ISSUE THREAD

**Issue by hymhub** [dcastil/tailwind-merge#469]
tailwind config:
```javascript
// tailwind.config.ts
export default {
// ...
  theme: {
    extend: {
      borderRadius: {
        layout: '16px'
      }
    }
  }
}
```
error:
```javascript
twMerge('rounded-layout', 'rounded-none')  // output -> rounded-layout rounded-none
twMerge('!rounded-layout', '!rounded-none')  // output -> !rounded-layout !rounded-none
```

**Comment by dcastil** [comment]
Hey @hymhub! 👋

Thanks for your patience, just came back from a vacation. tailwind-merge doesn't have access to the tailwind.config.ts file and you need to configure it separately so it knows about the rounded-layout class.

Here is an example on how to configure tailwind-merge: https://github.com/dcastil/tailwind-merge/blob/v2.5.2/docs/recipes.md#adding-custom-scale-from-tailwind-config-to-tailwind-merge-config.

And here is the documentation on how the tailwind-merge configuration works: https://github.com/dcastil/tailwind-merge/blob/v2.5.2/docs/configuration.md#usage-with-custom-tailwind-config.

---

(For myself)

Related: https://github.com/dcastil/tailwind-merge/issues/447, https://github.com/dcastil/tailwind-merge/issues/368, https://github.com/dcastil/tailwind-merge/discussions/322, https://github.com/dcastil/tailwind-merge/issues/321, https://github.com/dcastil/tailwind-merge/discussions/315, https://github.com/dcastil/tailwind-merge/issues/302, https://github.com/dcastil/tailwind-merge/issues/276, https://github.com/dcastil/tailwind-merge/discussions/275, https://github.com/dcastil/tailwind-merge/issues/274, https://github.com/dcastil/tailwind-merge/issues/250, https://github.com/dcastil/tailwind-merge/issues/207

**Comment by sylvainmouquet** [comment]
@hymhub if tailwind-merge don't fix the error, you can try [twindmerge](https://www.npmjs.com/package/twindmerge)  it's an alternative to tailwind-merge. I have added your test, it works well
