### ISSUE TITLE
Document how to install it, the package name

### ISSUE THREAD

**Issue by idc77** [dcastil/tailwind-merge#484]
### Describe the bug

This might sound like a beancounter issue, but I came from some issue where the solution had `twMerge` so I went and searched and found this repository.
But, maybe I'm blind, I don't see the package name anywhere.

So my suggestion is to add lines like

`npm i tailwind-merge`
`pnpm add tailwind-merge`
`yarn add tailwind-merge`
`bun install tailwind-merge`

Sometimes the packages are named differently than the repo name.

### Environment

-   tailwind-merge version: [e.g. 1.13.1]

**Comment by dcastil** [comment]
Makes sense, will add them to the configuration docs.
