### ISSUE TITLE
Export ConfigExtension type from package

### ISSUE THREAD

**Issue by dcastil** [dcastil/tailwind-merge#504]
_Originally posted by @stijns96 in https://github.com/dcastil/tailwind-merge/discussions/501_

**Comment by stijns96** [comment]
Hi @dcastil,

I'm currently waiting for this in my PR. Would be appreciated if you could let me know when we can expect a release.

**Comment by dcastil** [comment]
@stijns96 will do it right now

**Comment by stijns96** [comment]
@dcastil Thanks!
