### ISSUE TITLE
No link to the actual typing in the dist folder

### ISSUE THREAD

**Issue by navin-moorthy** [dcastil/tailwind-merge#74]
Actual path of the typing - dist/index.d.ts

**Bug**: Path found in package.json - ./dist/types/index.d.ts

Dist folder contents - https://unpkg.com/browse/tailwind-merge@1.1.0/dist/

![image](https://user-images.githubusercontent.com/39694575/146502446-e0a64ebc-3ce8-401b-8c82-b5948ac19cca.png)

**Comment by dcastil** [comment]
Thanks for pointing it out! 🙏 I just released [v1.1.1](https://github.com/dcastil/tailwind-merge/releases/tag/v1.1.1) with a fix. Can you check whether that one works?

**Comment by navin-moorthy** [comment]
Thanks, it works well now.
