### ISSUE TITLE
text classes get merged incorrectly

### ISSUE THREAD

**Issue by elkorn** [dcastil/tailwind-merge#97]
Examples:

`twMerge('text-red text-xxl')` outputs `text-xxl` instead of `text-red text-xxl`.
`twMerge('text-xxl text-red')` outputs `text-red` instead of `text-xxl text-red`.

Probably similar to #67.

**Comment by dcastil** [comment]
Hey @elkorn! 👋 

Did you create a custom config for tailwind-merge with `extendTailwindMerge`? The `text-xxl` class is not defined in the [default font-size classes](https://tailwindcss.com/docs/font-size) and is therefore treated as a color class which is causing the previous color class to get removed.

**Comment by elkorn** [comment]
Indeed - my bad. Sorry for the hassle and thanks for the great work! :)

**Comment by nightmareinc** [comment]
Hey @elkorn 
I have the same issue but can't seem to get this straight. could you please give me an example of how the `classGroups`  should look like?

here's what I've tried:
```
module.exports = {
  ...,
  theme: {
    fontSize: ({ theme }) => ({
      h1: ['58px', { fontWeight: theme('fontWeight.extraBold') }], // headline1
      h2: ['40px', { fontWeight: theme('fontWeight.bold') }], // headline2
    }),
    extend: {
      colors: {
        hawkes: {
          b100: '#DCDFE8',
          b80: '#E3E5ED',
          b60: '#EAECF1',
          b40: '#F1F2F6',
          b20: '#F8F9FA',
          b10: '#FFFFFF',
        },
      },
    },
  },
}
```
here's the merge output:
```
twMerge('text-h1', 'text-hawkes-b40') ---> text-hawkes-b40
```
I tried adding these `classGroups`, but didn't make a difference.
```
const newConfig = extendTailwindMerge({
  // ↓ Add values to existing class groups or define new ones
  classGroups: {
    'font-size': [{ text: 'h1' }],
    'font-color': [{ text: 'hawkes-b40' }],
  },
})
```

**Comment by dcastil** [comment]
Hey @nightmareinc! 👋 

You forgot to put `'h1'` into an array. You also don't need to add custom colors to tailwind-merge, e.g. any unknown classes starting with `text-` will be treated as colors.

This config worked when I tested it:

```js
const twMerge = extendTailwindMerge({
  classGroups: {
    'font-size': [{ text: ['h1', 'h2'] }],
  },
})

twMerge('text-h1', 'text-hawkes-b40')
// → returns 'text-hawkes-b40'
```
